### ISSUE TITLE
il tasto della scelta numero

### ISSUE THREAD

**Issue by Vinx92** [SF4NU/prova#11]
Ho notato che nel tasto della scelta del dado se vai troppe volte indietro dall'uno per arrivare a due devi fare due clic !
prova a darci un'occhiata

**Comment by Vinx92** [comment]
non va a zero la scelta del numero rimane scritto uno quando in realtà e a zero ma esce scritto lo stesso 1

**Comment by SF4NU** [comment]
> non va a zero la scelta del numero rimane scritto uno quando in realtà e a zero ma esce scritto lo stesso 1

devo controllare

**Comment by SF4NU** [comment]
> Ho notato che nel tasto della scelta del dado se vai troppe volte indietro dall'uno per arrivare a due devi fare due clic ! prova a darci un'occhiata

si l'avevo notato anch'io ma non capisco se è un bug del codice o no

**Comment by Vinx92** [comment]
Magari va in conflitto con quello scritto ma non lo so
