### ISSUE TITLE
scritta nella casella del dado

### ISSUE THREAD

**Issue by Vinx92** [SF4NU/prova#12]
dove scegli il numero del dado invece di scrivere 0 all'inizio o solo il numero durante la scelta, si può scrivere "FACCIA : " appena entra nel tavolo, quando inizia a scegliere il numero scrive "FACCIA : 1 " e cosi via, e un idea fammi sapere

**Comment by Vinx92** [comment]
se leggi l'issues prima di questo, non deve mai tornare a zero la scelta! oppure se vogliamo scrivere questa scritta non deve mai tornare a "FACCIA : " ma deve fermarsi a "FACCIA : 1" 
non so se mi sono spiegato ahahaha

**Comment by SF4NU** [comment]
> se leggi l'issues prima di questo, non deve mai tornare a zero la scelta! oppure se vogliamo scrivere questa scritta non deve mai tornare a "FACCIA : " ma deve fermarsi a "FACCIA : 1" non so se mi sono spiegato ahahaha

sinceramente non ho capito lol

**Comment by SF4NU** [comment]
> dove scegli il numero del dado invece di scrivere 0 all'inizio o solo il numero durante la scelta, si può scrivere "FACCIA : " appena entra nel tavolo, quando inizia a scegliere il numero scrive "FACCIA : 1 " e cosi via, e un idea fammi sapere

se intendi tra il + e il - allora penso che vada bene ma devi aggiungerlo tu
